server {
    listen 80;    
    # Logs
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    
    # Root directory points to public folder
    root /var/www;
    
    # Default index files
    index index.php index.html;
    
    # Increase max upload size
    client_max_body_size 2048M;
    
    # CORS headers
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type';
    
    # WordPress-specific rewrites
    location / {
        # First attempt to serve request as file, then as directory,
        # then fall back to index.php with query string
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
    
    # Pass PHP scripts to FastCGI server
    location ~ \.php$ {
        # Verify the file exists before passing to FastCGI
        try_files $uri =404;
        
        # FastCGI configuration
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # Set proper document root for WordPress
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Remove CORS header from PHP
        fastcgi_hide_header access-control-allow-origin;
        
        # Additional WordPress FastCGI params
        fastcgi_param HTTPS off; # Change to 'on' if using SSL
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }
    
    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    
    # Deny access to uploads that aren't images, videos, music, etc.
    location ~* ^/wp-content/uploads/.*.(html|htm|shtml|php|js|swf)$ {
        deny all;
    }
    
    # Deny access to wp-config.php file
    location ~* wp-config.php {
        deny all;
    }
    
    # Cache static files
    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}